Add env

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,25 +1,28 @@
 ### https://github.com/vercel/next.js/tree/canary/examples/with-docker
 
 # Install dependencies only when needed
-FROM node:16-alpine AS deps
+FROM node:18-alpine AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
 # Install dependencies based on the preferred package manager
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-RUN \
-    # Yarn 1 vs Yarn 2+, no `--frozen-lockfile` flag
-    # if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    if [ -f yarn.lock ]; then yarn; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
+# COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+# RUN \
+#     # Yarn 1 vs Yarn 2+, no `--frozen-lockfile` flag
+#     # if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#     if [ -f yarn.lock ]; then yarn; \
+#     elif [ -f package-lock.json ]; then npm ci; \
+#     elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+#     else echo "Lockfile not found." && exit 1; \
+#     fi
+COPY package.json yarn.lock* ./
+RUN ["yarn", "set", "version", "berry"]
+RUN ["yarn"]
 
 
 # Rebuild the source code only when needed
-FROM node:16-alpine AS builder
+FROM node:18-alpine AS builder
 WORKDIR /app
 # COPY --from=deps /app/node_modules ./node_modules
 COPY --from=deps /app/.yarn ./.yarn
@@ -36,7 +39,7 @@ RUN yarn build
 # RUN npm run build
 
 # Production image, copy all the files and run next
-FROM node:16-alpine AS runner
+FROM node:18-alpine AS runner
 WORKDIR /app
 
 ENV NODE_ENV production
